<?php
/**
 * @var \MageSuite\ProductTile\Block\Tile\Fragment|\Magento\Catalog\Block\Product\View\Description|\MageSuite\BrandManagement\Block\Checkout\Cart\Item\Renderer\Brand $block
 * @var \MageSuite\BrandManagement\ViewModel\BrandVisibility $viewModel
 */
$viewModel = $block->getViewModel();
$product = $block->getProduct();
if ($viewModel instanceof \MageSuite\BrandManagement\ViewModel\BrandVisibility && $viewModel->isVisible($block->getLocation())) {
    $brand = $product instanceof \Magento\Catalog\Api\Data\ProductInterface && $product->getData('brand') ? $product->getAttributeText('brand') : '';
}
?>
<?php if ($brand): ?>
    <?php
    $brandTag = $block->getWrapperTag() ?? 'div';

    $brandClass = $block->getWrapperCssClass();
    $brandClass = $brandClass ? sprintf('class="%s"', $brandClass) : '';

    $brandTextClass = $block->getTextCssClass();
    $brandTextClass = $brandTextClass ? sprintf('class="%s"', $brandTextClass) : '';
    ?>
    <<?= $brandTag ?> <?= $brandClass ?>>
    <span <?= $brandTextClass ?>
        <?php if ($block->getLocation() === \MageSuite\BrandManagement\Helper\Configuration::BRAND_VISIBILITY_PDP): ?> itemprop="brand"<?php endif ?>>
        <?= $brand ?>
    </span>
    </<?= $brandTag ?>>
<?php endif; ?>
